/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as ConclusionRouteImport } from './routes/conclusion'
import { Route as ContentRouteImport } from './routes/content'
import { Route as ConversionRouteImport } from './routes/conversion'
import { Route as GeoRouteImport } from './routes/geo'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as MeasurementRouteImport } from './routes/measurement'
import { Route as RedesignRouteImport } from './routes/redesign'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SerpRouteImport } from './routes/serp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const ConclusionRoute = ConclusionRouteImport.update({
  id: '/conclusion',
  path: '/conclusion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversionRoute = ConversionRouteImport.update({
  id: '/conversion',
  path: '/conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoRoute = GeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementRoute = MeasurementRouteImport.update({
  id: '/measurement',
  path: '/measurement',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesignRoute = RedesignRouteImport.update({
  id: '/redesign',
  path: '/redesign',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SerpRoute = SerpRouteImport.update({
  id: '/serp',
  path: '/serp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/competitors': typeof CompetitorsRoute
  '/conclusion': typeof ConclusionRoute
  '/content': typeof ContentRoute
  '/conversion': typeof ConversionRoute
  '/geo': typeof GeoRoute
  '/keywords': typeof KeywordsRoute
  '/measurement': typeof MeasurementRoute
  '/redesign': typeof RedesignRoute
  '/roadmap': typeof RoadmapRoute
  '/serp': typeof SerpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/competitors': typeof CompetitorsRoute
  '/conclusion': typeof ConclusionRoute
  '/content': typeof ContentRoute
  '/conversion': typeof ConversionRoute
  '/geo': typeof GeoRoute
  '/keywords': typeof KeywordsRoute
  '/measurement': typeof MeasurementRoute
  '/redesign': typeof RedesignRoute
  '/roadmap': typeof RoadmapRoute
  '/serp': typeof SerpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/competitors': typeof CompetitorsRoute
  '/conclusion': typeof ConclusionRoute
  '/content': typeof ContentRoute
  '/conversion': typeof ConversionRoute
  '/geo': typeof GeoRoute
  '/keywords': typeof KeywordsRoute
  '/measurement': typeof MeasurementRoute
  '/redesign': typeof RedesignRoute
  '/roadmap': typeof RoadmapRoute
  '/serp': typeof SerpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/competitors'
    | '/conclusion'
    | '/content'
    | '/conversion'
    | '/geo'
    | '/keywords'
    | '/measurement'
    | '/redesign'
    | '/roadmap'
    | '/serp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/competitors'
    | '/conclusion'
    | '/content'
    | '/conversion'
    | '/geo'
    | '/keywords'
    | '/measurement'
    | '/redesign'
    | '/roadmap'
    | '/serp'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/competitors'
    | '/conclusion'
    | '/content'
    | '/conversion'
    | '/geo'
    | '/keywords'
    | '/measurement'
    | '/redesign'
    | '/roadmap'
    | '/serp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CompetitorsRoute: typeof CompetitorsRoute
  ConclusionRoute: typeof ConclusionRoute
  ContentRoute: typeof ContentRoute
  ConversionRoute: typeof ConversionRoute
  GeoRoute: typeof GeoRoute
  KeywordsRoute: typeof KeywordsRoute
  MeasurementRoute: typeof MeasurementRoute
  RedesignRoute: typeof RedesignRoute
  RoadmapRoute: typeof RoadmapRoute
  SerpRoute: typeof SerpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conclusion': {
      id: '/conclusion'
      path: '/conclusion'
      fullPath: '/conclusion'
      preLoaderRoute: typeof ConclusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversion': {
      id: '/conversion'
      path: '/conversion'
      fullPath: '/conversion'
      preLoaderRoute: typeof ConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo': {
      id: '/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof GeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurement': {
      id: '/measurement'
      path: '/measurement'
      fullPath: '/measurement'
      preLoaderRoute: typeof MeasurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redesign': {
      id: '/redesign'
      path: '/redesign'
      fullPath: '/redesign'
      preLoaderRoute: typeof RedesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serp': {
      id: '/serp'
      path: '/serp'
      fullPath: '/serp'
      preLoaderRoute: typeof SerpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CompetitorsRoute: CompetitorsRoute,
  ConclusionRoute: ConclusionRoute,
  ContentRoute: ContentRoute,
  ConversionRoute: ConversionRoute,
  GeoRoute: GeoRoute,
  KeywordsRoute: KeywordsRoute,
  MeasurementRoute: MeasurementRoute,
  RedesignRoute: RedesignRoute,
  RoadmapRoute: RoadmapRoute,
  SerpRoute: SerpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
